name: Pipeline with Stages

on:
  push:
      branches:
        - 'main'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: build project
              run: echo "Building the project...."
    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: test project
              run: echo "running tests....."
    deploy:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: deploy project
              run: echo "Deploying the project...."a